schema_version: 1

context:
  version: "8.0.0"

package:
  name: complexipy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/complexipy/complexipy-${{ version }}.tar.gz
  sha256: 29d187c603ec4a5195f3352fbd83dcc7172194ea19e5b79a8f0e64056b751926

build:
  number: 0
  script:
    - if: win
      then: git config --system core.longpaths true
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - complexipy = complexipy.cli:main

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - git
  host:
    - python
    - maturin >=1.9.4,<2.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - complexipy
      pip_check: true
  - script:
      - complexipy --help

about:
  summary: An extremely fast Python library to calculate the cognitive complexity of Python files, written in Rust.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/rohaquinlop/complexipy
  documentation: https://rohaquinlop.github.io/complexipy/

extra:
  recipe-maintainers:
    - thewchan
