schema_version: 1

context:
  version: "5.6.1"

package:
  name: complexipy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/complexipy/complexipy-${{ version }}.tar.gz
  sha256: c87e931e648eddab5f4b9eb1fcbbc7cf6de5840f7d8d65b6ae49364b0d9b561d

build:
  number: 0
  script:
    - if: win
      then: git config --system core.longpaths true
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - complexipy = complexipy.main:app

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - git
  host:
    - python
    - maturin >=1.9.4,<2.0
    - pip
  run:
    - python
    - tomli >=2.2.1
    - typer >=0.12.5

tests:
  - python:
      imports:
        - complexipy
      pip_check: true
  - script:
      - complexipy --help

about:
  summary: An extremely fast Python library to calculate the cognitive complexity of Python files, written in Rust.
  license: MIT
  license_file:
    - LICENSE
    - vscode/complexipy/LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/rohaquinlop/complexipy
  documentation: https://rohaquinlop.github.io/complexipy/

extra:
  recipe-maintainers:
    - thewchan
